### ISSUE TITLE
failed to build 4.4.60 via buildroot

### ISSUE THREAD

**Issue by trusch** [dh-electronics/linux-imx6qdl#1]
What did you do?

Use the dev/4.4.60 branch as kernel in buildroot.

What did happen?

The build failed due to missing struct definitions:

```
  CC      drivers/pwm/pwm-fsl-ftm.o
drivers/pwm/pwm-fsl-ftm.c: In function 'fsl_pwm_probe':
drivers/pwm/pwm-fsl-ftm.c:446:11: error: 'struct pwm_chip' has no member named 'of_pwm_n_cells'
  fpc->chip.of_pwm_n_cells = 3;
           ^
```

**Comment by cniedermaier** [comment]
Did you use your config imx6_dhcom_defconfig?
Which commit is still working?

**Comment by jaapcrezee** [comment]
It seems this got broken by commit 4d580464a71052ac204c5e6bed61c7276af36cdf ?

**Comment by cniedermaier** [comment]
Issue is closed. If it is still relevant, please test with a newer kernel or reopen the issue.
